# Generated by Django 2.1.15 on 2020-02-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingwip', '0002_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='contract_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='cost_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='cost_to_finish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='finish_estimation',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='invoice_sent',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='invoice_sent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='paid_by_customer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='pic',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='unpaid_by_customer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='wom',
            field=models.CharField(max_length=6),
        ),
    ]
