# Generated by Django 2.1.15 on 2020-02-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingwip', '0003_auto_20200226_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='note',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='contract_value',
            field=models.IntegerField(default=0, verbose_name='Total Contract'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='cost_paid',
            field=models.IntegerField(default=0, verbose_name='Cost Paid'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='cost_to_finish',
            field=models.IntegerField(default=0, verbose_name='Cost To Finish'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='deadline',
            field=models.DateTimeField(default=None, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='finish_estimation',
            field=models.DateTimeField(default=None, null=True, verbose_name='Finish Estimation'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='invoice_sent',
            field=models.DateTimeField(default=None, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='invoice_sent_days',
            field=models.IntegerField(default=0, verbose_name='days to collect'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='paid_by_customer',
            field=models.IntegerField(default=0, verbose_name='Paid by Customer'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='unpaid_by_customer',
            field=models.IntegerField(default=0, verbose_name='Customer Debt'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='wom',
            field=models.CharField(max_length=6, verbose_name='Main WIP'),
        ),
    ]
