# Generated by Django 2.1.15 on 2020-02-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingwip', '0004_auto_20200227_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='deadline',
            field=models.DateField(default=None, null=True, verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='finish_estimation',
            field=models.DateField(default=None, null=True, verbose_name='Finish Estimation'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='invoice_sent',
            field=models.DateField(default=None, null=True, verbose_name='Invoice Date'),
        ),
    ]
