# Generated by Django 2.1.15 on 2020-02-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackingwip', '0005_auto_20200227_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='contract_value',
            field=models.FloatField(default=0, verbose_name='Total Contract'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='cost_paid',
            field=models.FloatField(default=0, verbose_name='Cost Paid'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='cost_to_finish',
            field=models.FloatField(default=0, verbose_name='Cost To Finish'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='invoice_sent_days',
            field=models.FloatField(default=0, verbose_name='days to collect'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='paid_by_customer',
            field=models.FloatField(default=0, verbose_name='Paid by Customer'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='unpaid_by_customer',
            field=models.FloatField(default=0, verbose_name='Customer Debt'),
        ),
    ]
